"""add users github_token_encrypted

Revision ID: 6e0d43f6c925
Revises: 209e164db2d8
Create Date: 2026-10-08 05:29:34.932476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0d43f6c925'
down_revision: Union[str, Sequence[str], None] = '209e164db2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_token_encrypted')
    # ### end Alembic commands ###
