"""add index on issues repository_id state

Revision ID: 8a58755b025b
Revises: 06dbdb9ae372
Create Date: 2026-10-06 01:47:20.636971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a58755b025b'
down_revision: Union[str, Sequence[str], None] = '06dbdb9ae372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_issues_repository_id_state', 'issues', ['repository_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issues_repository_id_state', table_name='issues')
    # ### end Alembic commands ###
