"""add tool_calls pending_actions and model_call investigation link

Revision ID: dddf7bdaa2d5
Revises: a15c34ebe11c
Create Date: 2026-10-08 05:09:14.296358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dddf7bdaa2d5'
down_revision: Union[str, Sequence[str], None] = 'a15c34ebe11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('result_size', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_investigation_id', 'tool_calls', ['investigation_id'], unique=False)
    op.add_column('model_calls', sa.Column('investigation_id', sa.Integer(), nullable=True))
    op.create_index('ix_model_calls_created_at', 'model_calls', ['created_at'], unique=False)
    op.create_index('ix_model_calls_investigation_id', 'model_calls', ['investigation_id'], unique=False)
    op.create_foreign_key('fk_model_calls_investigation_id', 'model_calls', 'investigations', ['investigation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_model_calls_investigation_id', 'model_calls', type_='foreignkey')
    op.drop_index('ix_model_calls_investigation_id', table_name='model_calls')
    op.drop_index('ix_model_calls_created_at', table_name='model_calls')
    op.drop_column('model_calls', 'investigation_id')
    op.drop_index('ix_tool_calls_investigation_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
